---
output: rmarkdown::github_document
always_allow_html: yes
bibliography: inst/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  dpi = 300,
  fig.height = 6, 
  fig.width = 6
)
```

# TreeTracer `r emo::ji("tree")` `r emo::ji("pen")`

The beginnings...

TreeTracer is an R package for creating trace plots of trees from random forests fit using the randomForest R package. Trace plots are useful tools for visually comparing trees from a random forest. See @urbanek:2008 for additional information about trace plots. 

Examples:

```{r}
# Load the package
library(TreeTracer)
```

```{r message = FALSE}
# Load other packages
library(dplyr)
library(ggpcp)
library(ggplot2)
```

```{r}
# Load the Palmer penguins data
penguins <- na.omit(palmerpenguins::penguins)
```

```{r fig.width = 6, fig.height = 3}
# Create a parallel coordinate plot of features that will be used to fit
# a random forest colored by the variable of interest to predict (species)
penguins %>%
  ggplot(aes(color = species)) +
  geom_pcp(aes(
    vars = vars(bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g)
  ), alpha = 0.5) + 
  scale_color_brewer(palette = "Paired")
```

```{r}
# Fit a random forest
set.seed(71)
penguin.rf <-
  randomForest::randomForest(
    species ~ bill_length_mm + bill_depth_mm + flipper_length_mm + body_mass_g,
    data = penguins, 
    ntree = 50
  )
```

```{r}
# Generate a trace plot of the first 10 trees in the forest
trace_plot(
  rf = penguin.rf,
  train = penguins %>% select(bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g),
  tree_ids = 1:10
)
```

```{r}
# Plot all trees in the forest and adjust alpha
trace_plot(
  rf = penguin.rf,
  train = penguins %>% select(bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g),
  tree_ids = 1:penguin.rf$ntree,
  alpha = 0.05
)
```

```{r fig.width = 16, fig.height = 4}
# Compute fit metrics between all trees
fit_metrics = compute_fit_metric(penguin.rf, penguins)
head(fit_metrics)

dist_matrix <- get_dist_matrix(fit_metrics)

stree <- hclust(dist_matrix, method = "single")
ctree <- hclust(dist_matrix, method = "complete")
atree <- hclust(dist_matrix, method = "average")

par(mfcol=c(1,3))
plot(stree, ylab = "Distance", main = "Single linkage")
plot(ctree, ylab = "Distance", main = "Complete linkage")
plot(atree, ylab = "Distance", main = "Average linkage")
```

```{r}
# Plot all trees in the forest and adjust alpha
trace_plot(
  rf = penguin.rf,
  train = penguins %>% select(bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g),
  tree_ids = c(12, 32, 35), 
  color_by_id = TRUE
) + 
  scale_color_manual(values = c("purple", "orange", "darkorange"))
```

## References

